### ISSUE TITLE
ARCHITECTURE="raspberry"

### ISSUE THREAD

**Issue by christianTF** [joesie/GPIO#1]
https://github.com/joesie/io/blob/3974af74366815ffe0dd2fe18599d3353c8e5ff3/plugin.cfg#L73

Ein GPIO-Plugin kann nur auf einem Raspberry laufen.

`ARCHITECTURE="raspberry"`

**Comment by joesie** [comment]
Ja perfekt. Da hätte ich nicht dran gedacht. Gutes Flag.

ist mit dem nächsten commit gefixt.
