### ISSUE TITLE
plugin.cfg: "and use lowercase only"

### ISSUE THREAD

**Issue by christianTF** [joesie/GPIO#2]
Bitte `name` und `title` lowercase schreiben (steht auch so ein paar Zeilen darüber)
Das kann sonst Probleme mit der Pluginerkennung von LoxBerry::System geben.

https://github.com/joesie/io/blob/3974af74366815ffe0dd2fe18599d3353c8e5ff3/plugin.cfg#L26

**Comment by joesie** [comment]
Besten Dank. Ich dachte der Title ist der Pretty Print des Plugins und der für den Anwender angezeigte Text.

Hab es mit dem nächsten commit gefixt.
