### ISSUE TITLE
External MQTT Broker

### ISSUE THREAD

**Issue by mschlenstedt** [joesie/GPIO#28]
Add option to use an external MQTT Broker (e. g. MQTT Gateway Plugin running on another LoxBerry).

**Comment by christianTF** [comment]
Ich würde den Commit reverten.
Die Infrastruktur ist so vorgesehen, dass es externe Broker gibt:
https://www.loxwiki.eu/display/LOXBERRY/Using+multiple+LoxBerry%27s+with+a+single+MQTT+broker

Ein Plugin braucht KEINE eigene MQTT-Konfiguration, um einen anderen Broker zu verwenden.

Das bedeutet nur _wieder_ eigene Pflege im Plugin.
Die Funktion „as-is“ war auch mit Jörg abgestimmt und die Implementierung die Beispielimplementierung für Python. 
Das Plugin Soll keine UI für MQTT benötigen.

**Comment by mschlenstedt** [comment]
Machen wir doch überall so?! Auch im Nuki. Warum soll ich das MQTT Gateway zig mal installieren, wenn ich es nur einmal brauche?

**Comment by mschlenstedt** [comment]
Ist reverted. Verstehe es nicht und finde es extrem kompliziert überall das Gateway zu installieren, das dann wieder nur an das externe Gateway forwarded. Nun sind die Einstellungen auf zwei Plugins verteilt. Steigt aus meiner Sicht auch niemand durch. Ressourcen verbraucht es auch.  Anstelle von 4 Optionen im Config mit Null Pflegeaufwand zu setzen. Aber sei es drum = wenn es so sein soll...


Ich werde das bei mir definitiv nicht so umsetzen.
