### ISSUE TITLE
Bitte die LoxBerry Systemvariablen benutzen

### ISSUE THREAD

**Issue by christianTF** [joesie/GPIO#3]
https://github.com/joesie/io/blob/3974af74366815ffe0dd2fe18599d3353c8e5ff3/webfrontend/htmlauth/index.cgi#L53

Wenn du LoxBerry::System includest, hast du immer die Pfade zu deinem Plugin als Variablen verfügbar.

Z.B. `$lbphtmlauthdir` zeigt immer in dein htmlauth, oder `$lbpbindir` zu deinen bin's.

Alle Variablen, die's gibt, stehen hier: https://www.loxwiki.eu/display/LOXBERRY/Perl-Modul+LoxBerry%3A%3ASystem

Grundsätzlich solltest du nie absolute Pfade, sondern Variablen verwenden. Michael's System bei der Plugininstallation kann den Pfad eines Plugins ändern, wenn ein Ordner nicht unique ist. Mit den Variablen ist sichergestellt, dass du immer in "deinen" Verzeichnissen operierst.

EDIT/PS: Das sind halt so Feinheiten, aber ist erstmal nicht so gravierend, aber langfristig besser :-)

**Comment by joesie** [comment]
mit dem nächsten commit gefixt. Besten Dank
