### ISSUE TITLE
Ich schreib mal hier - zu spät für WhatsApp Gebimmel :-)

### ISSUE THREAD

**Issue by christianTF** [joesie/GPIO#4]
Hat ein wenig gedauert - ich war die Woche im Ausland, und heute musste ich auch noch Miniserver-SD-Karte tauschen (kaputt), und trotzdem auch das Wetter ausnutzen :-)

Ich hab leider keine Relais am Pi, deswegen habe ich keinen Live-Test mit Relais machen können.
Ein paar Sachen habe ich dir eh als Issues erstellt.

Beim Einrichten hab ich nicht recht gewusst, was ich in die Felder hineinschreiben soll. Oben war mir klar, aber unten? Ich habe dann im Code nachgeschaut, und das ist somit einfach die GPIO-Nummer. Wäre es nicht logischer, wenn ich als Parameter gleich die GPIO-Nummer mitgebe, statt die Nummer vom Plugin?

Das Senden funktioniert, cool wäre noch, wenn auch bei OK ein Text als Result käme.
Ob das, was ich sende, ankommt, weiß ich nicht genau, wie ich das prüfen kann. 

Beim Speichern der Ausgangsnummern bekomme ich einen Fehler 500, aber gespeichert wird trotzdem. Ich habe 0, 1, 2 probiert
![image](https://user-images.githubusercontent.com/14220265/46263084-dcd39a00-c50a-11e8-8101-16a34f5b4616.png)

Dann hab ich noch gesehen, dass mir das Plugin bei jedem Reboot eine Notification sendet (Siiehe Screenshot). Das kommt definitiv von dir, weil ich habe gar kein Sonos ;-)

![image](https://user-images.githubusercontent.com/14220265/46263038-296aa580-c50a-11e8-835f-11ace8f8763a.png)

Das GUI und die falschen Eingaben der Benutzer sind das Schwierigste! :-)

lg, Christian

**Comment by joesie** [comment]
Alle Punkte umgesetzt ;)
