### ISSUE TITLE
troubleshooting mit plugin "MQTT"

### ISSUE THREAD

**Issue by Mika2814** [joesie/GPIO#7]
Hallo, bei mir ist folgender Fehler aufgetreten:
Ich übertrage 1-Wire Temperatursensoren über den Mosquitto Broker. Als ich danach dein GPIO plugin installiert habe, konnte sich der Broker nicht mehr anmelden. Möglicherweise besteht hier ein Port Problem. 

lg Michael

**Comment by joesie** [comment]
Fixed with latest version
